image: Visual Studio 2019

before_build:

  - cd c:/projects

  - curl -fsSL -o sfml.zip https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip
  - 7z x sfml.zip
  - rename SFML-2.5.1 sfml

  - git clone --depth 1 https://github.com/jagoly/sqee.git
  - cd c:/projects/sqee
  - cmake . -DCMAKE_PREFIX_PATH=c:/projects/sfml -G "Visual Studio 16 2019" -A x64
  - cmake --build . --target sqee

build_script:

  - cd c:/projects/SuperTuxSmash

  - cmake . -G "Visual Studio 16 2019" -A x64
  - cmake --build .

after_build:

  - cd C:\
  
  - dir MSVCP140D.dll /s
  - dir VCRUNTIME140D.dll /s
  - dir VCRUNTIME140_1D.dll /s
  - dir ucrtbased.dll /s

  - mkdir out
  
  - copy c:\projects\sfml\bin\openal32.dll out
  - copy c:\projects\sfml\bin\sfml-audio-d-2.dll out
  - copy c:\projects\sfml\bin\sfml-system-d-2.dll out
  - copy c:\projects\sfml\bin\sfml-window-d-2.dll out
  
  - copy c:\projects\sqee\Debug\sqee.dll out
  - copy c:\projects\sqee\lua54cpp\Debug\lua54cpp.dll out

  - copy c:\projects\SuperTuxSmash\Debug\sts-game.exe out

  - copy c:\projects\SuperTuxSmash\player1.json out
  - copy c:\projects\SuperTuxSmash\player2.json out
  - copy c:\projects\SuperTuxSmash\player3.json out
  - copy c:\projects\SuperTuxSmash\player4.json out

  - xcopy /E c:\projects\SuperTuxSmash\assets out\assets\
  - xcopy /E c:\projects\SuperTuxSmash\shaders out\shaders\
  
  - rename out sts-windows-debug

  - 7z a sts-windows-debug.zip sts-windows-debug

artifacts:

  - path: sts-windows-debug.zip
    name: sts-windows-debug

