os: linux
dist: focal
language: cpp

addons:
  apt:
    packages:
      - libglfw3-dev

before_script:
  - cd /home/travis/build/jagoly

  - wget -O vulkan-sdk.tar.gz https://sdk.lunarg.com/sdk/download/1.2.170.0/linux/vulkansdk-linux-x86_64-1.2.170.0.tar.gz
  - tar -xzf vulkan-sdk.tar.gz
  - source 1.2.170.0/setup-env.sh

  - git clone --depth 1 --branch master https://github.com/jagoly/sqee.git
  - cd sqee
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake ..
  - cmake --build . --target sqee

script:
  - cd /home/travis/build/jagoly/SuperTuxSmash
  - mkdir build && cd build
  - cmake .. -DSQEE_BUILD_ROOT=/home/travis/build/jagoly/sqee/build
  - cmake --build .

