os: linux
dist: focal
language: cpp

addons:
  apt:
    packages:
      - libsfml-system2.5
      - libsfml-window2.5
      - libsfml-dev
      - libglfw3-dev

before_script:
  - cd /home/travis/build/jagoly
  - git clone --depth 1 https://github.com/jagoly/sqee.git
  - mkdir sqee/build && cd sqee/build
  - cmake ..
  - cmake --build . --target sqee

script:
  - cd /home/travis/build/jagoly/SuperTuxSmash
  - mkdir build && cd build
  - cmake .. -DSQEE_BUILD_ROOT=/home/travis/build/jagoly/sqee/build
  - cmake --build .

