function tick()
  action: wait_until(4)
  action: enable_blob_group(0)
  action: emit_particles('PuffA', 40)
  action: wait_until(8)
  action: disable_blob_group(0)
  action: enable_blob_group(1)
  action: emit_particles('PuffB', 40)
  action: wait_until(12)
  action: disable_blob_group(1)
  action: enable_blob_group(2)
  action: emit_particles('PuffC', 50)
  action: wait_until(16)
  action: disable_blob_group(2)
  action: wait_until(28)
  action: allow_interrupt()
end
