function tick()
  action:wait_until(5)
  fighter.autocancel = false
  action:enable_blob_group(0)
  action:wait_until(6)
  action:disable_blob_group(0)
  action:wait_until(7)
  action:enable_blob_group(1)
  action:wait_until(8)
  action:disable_blob_group(1)
  action:wait_until(9)
  action:enable_blob_group(2)
  action:wait_until(10)
  action:disable_blob_group(2)
  action:wait_until(11)
  action:enable_blob_group(3)
  action:wait_until(12)
  action:disable_blob_group(3)
  action:wait_until(13)
  action:enable_blob_group(4)
  action:wait_until(14)
  action:disable_blob_group(4)
  action:wait_until(25)
  action:enable_blob_group(5)
  action:wait_until(26)
  action:disable_blob_group(5)
  action:wait_until(33)
  fighter.autocancel = true
  action:wait_until(38)
  action:allow_interrupt()
end

function cancel()
  fighter.autocancel = true
end