#version 450

#define OPTION_TANGENTS 1
#define OPTION_TEXTURE_DIFFUSE 1
#define OPTION_TEXTURE_SPECULAR 0
#define OPTION_TEXTURE_MASK 0
#define OPTION_TEXTURE_NORMAL 0
#define OPTION_SUB_SURFACE_SCATTER 0

#include "../BasicModel.frag.glsl"
